// @vitest-environment jsdom

import { cleanup, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, expect, test, vi } from "vitest";
import { UpdateToast } from "./UpdateToast";

// The register module is generated by the PWA plugin at build time; jsdom has no service worker.
const mocks = vi.hoisted(() => ({ useRegisterSW: vi.fn() }));

vi.mock("virtual:pwa-register/react", () => ({
  useRegisterSW: mocks.useRegisterSW,
}));

/** Builds a fresh useRegisterSW mock return so each test owns its own spies and starting state. */
function mockRegisterSW(needRefresh: boolean) {
  const setNeedRefresh = vi.fn();
  const updateServiceWorker = vi.fn(() => Promise.resolve());
  mocks.useRegisterSW.mockReturnValue({
    needRefresh: [needRefresh, setNeedRefresh],
    offlineReady: [false, vi.fn()],
    updateServiceWorker,
  });
  return { setNeedRefresh, updateServiceWorker };
}

afterEach(cleanup);

test("a waiting update shows the toast; refresh applies it and close dismisses it", async () => {
  const { setNeedRefresh, updateServiceWorker } = mockRegisterSW(true);
  render(<UpdateToast />);
  const toast = screen.getByRole("status");
  expect(toast.textContent).toContain("새 버전이 있어요.");
  await userEvent.click(screen.getByRole("button", { name: "새로고침" }));
  expect(updateServiceWorker).toHaveBeenCalledTimes(1);
  await userEvent.click(screen.getByRole("button", { name: "닫기" }));
  expect(setNeedRefresh).toHaveBeenCalledWith(false);
});

test("nothing renders while no update is waiting", () => {
  mockRegisterSW(false);
  render(<UpdateToast />);
  expect(screen.queryByRole("status")).toBeNull();
});
