// @vitest-environment jsdom

import { cleanup, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, expect, test, vi } from "vitest";
import { UpdateToast } from "./UpdateToast";

// The register module is generated by the PWA plugin at build time; jsdom has no service worker.
const sw = vi.hoisted(() => ({
  needRefresh: true,
  setNeedRefresh: vi.fn(),
  updateServiceWorker: vi.fn(() => Promise.resolve()),
}));

vi.mock("virtual:pwa-register/react", () => ({
  useRegisterSW: () => ({
    needRefresh: [sw.needRefresh, sw.setNeedRefresh],
    offlineReady: [false, vi.fn()],
    updateServiceWorker: sw.updateServiceWorker,
  }),
}));

afterEach(cleanup);

test("a waiting update shows the toast; refresh applies it and close dismisses it", async () => {
  render(<UpdateToast />);
  const toast = screen.getByRole("status");
  expect(toast.textContent).toContain("새 버전이 있어요.");
  await userEvent.click(screen.getByRole("button", { name: "새로고침" }));
  expect(sw.updateServiceWorker).toHaveBeenCalledTimes(1);
  await userEvent.click(screen.getByRole("button", { name: "닫기" }));
  expect(sw.setNeedRefresh).toHaveBeenCalledWith(false);
});

test("nothing renders while no update is waiting", () => {
  sw.needRefresh = false;
  render(<UpdateToast />);
  expect(screen.queryByRole("status")).toBeNull();
});
