// Monster catalog, weakest to strongest in `MONSTER_IDS` order.
// Ranges: hp 4..60, attack 1..12, defense 8..22 (d20 target), fleeDc 8..20, xp 2..30, gold 0..120.
// `hp` and `attack` never decrease along the list. `drop` is omitted (not undefined) when absent.

import type { Monster } from "../engine/types";
import type { MonsterId } from "./ids";

export const MONSTERS: Readonly<Record<MonsterId, Monster>> = {
  wild_boar: {
    id: "wild_boar",
    name: "멧돼지",
    description: "숲길에서 마주친 멧돼지. 이쪽이 비켜 줄 생각이 없다는 걸 알아채고 먼저 달려든다.",
    hp: 4,
    attack: 1,
    defense: 8,
    fleeDc: 8,
    xpReward: 2,
    goldReward: 0,
  },
  road_bandit: {
    id: "road_bandit",
    name: "노상강도",
    description: "길목을 지키는 좀도둑. 통행세라고 부르지만, 세금이 아니라는 건 둘 다 안다.",
    hp: 6,
    attack: 2,
    defense: 9,
    fleeDc: 9,
    xpReward: 3,
    goldReward: 8,
  },
  giant_rat: {
    id: "giant_rat",
    name: "거대 쥐",
    description: "개만 한 쥐. 도시 하수도가 그동안 무엇을 먹고 살았는지 보여 주는 증거다.",
    hp: 7,
    attack: 2,
    defense: 9,
    fleeDc: 8,
    xpReward: 3,
    goldReward: 2,
  },
  cave_bat: {
    id: "cave_bat",
    name: "동굴 박쥐",
    description: "동굴 천장에서 쏟아져 내리는 박쥐 떼. 한 마리는 우습고, 수십 마리는 우습지 않다.",
    hp: 8,
    attack: 2,
    defense: 11,
    fleeDc: 10,
    xpReward: 4,
    goldReward: 0,
  },
  goblin_scout: {
    id: "goblin_scout",
    name: "고블린 정찰병",
    description: "작고 빠르고 시끄럽다. 여기서 놓치면 곧 친구들을 데리고 돌아온다.",
    hp: 10,
    attack: 3,
    defense: 10,
    fleeDc: 10,
    xpReward: 5,
    goldReward: 10,
    drop: "short_bow",
  },
  goblin_chief: {
    id: "goblin_chief",
    name: "고블린 족장",
    description:
      "남의 투구를 쓰고 남의 칼을 든 고블린 두목. 훔친 물건으로 이만큼 위엄을 낸 것은 인정할 만하다.",
    hp: 14,
    attack: 4,
    defense: 12,
    fleeDc: 11,
    xpReward: 7,
    goldReward: 25,
    drop: "iron_mace",
  },
  gray_wolf: {
    id: "gray_wolf",
    name: "회색 늑대",
    description: "굶주린 회색 늑대. 눈이 마주쳤다면 도망칠 기회는 이미 지나간 것이다.",
    hp: 15,
    attack: 4,
    defense: 12,
    fleeDc: 13,
    xpReward: 7,
    goldReward: 0,
  },
  bog_slime: {
    id: "bog_slime",
    name: "늪 슬라임",
    description: "늪에서 스며 나온 끈적한 덩어리. 느리지만 집요하고, 베어도 별로 신경 쓰지 않는다.",
    hp: 18,
    attack: 4,
    defense: 11,
    fleeDc: 9,
    xpReward: 8,
    goldReward: 4,
  },
  skeleton_guard: {
    id: "skeleton_guard",
    name: "해골 경비병",
    description: "죽은 지 백 년이 지나도 초소를 지키는 해골. 교대 근무자가 오지 않았을 뿐이다.",
    hp: 20,
    attack: 5,
    defense: 14,
    fleeDc: 11,
    xpReward: 10,
    goldReward: 15,
    drop: "guard_saber",
  },
  restless_ghost: {
    id: "restless_ghost",
    name: "떠도는 유령",
    description: "이승에 미련이 남은 영혼. 무슨 미련인지 들어 줄 여유는 이쪽에 없다.",
    hp: 22,
    attack: 5,
    defense: 15,
    fleeDc: 12,
    xpReward: 11,
    goldReward: 0,
    drop: "holy_water",
  },
  hill_troll: {
    id: "hill_troll",
    name: "언덕 트롤",
    description:
      "바위만 한 주먹을 가진 트롤. 머리는 나쁘지만 상처가 아무는 속도는 머리보다 훨씬 낫다.",
    hp: 26,
    attack: 6,
    defense: 14,
    fleeDc: 13,
    xpReward: 13,
    goldReward: 30,
  },
  harpy: {
    id: "harpy",
    name: "하피",
    description: "여자의 얼굴과 새의 몸을 가진 괴물. 노래는 아름답고, 발톱은 그렇지 않다.",
    hp: 28,
    attack: 6,
    defense: 16,
    fleeDc: 15,
    xpReward: 14,
    goldReward: 20,
  },
  bandit_captain: {
    id: "bandit_captain",
    name: "산적 두목",
    description:
      "산적 무리를 이끄는 두목. 부하들이 도망칠 때도 혼자 남아 싸우는 것은 용기라기보다 자존심이다.",
    hp: 30,
    attack: 7,
    defense: 16,
    fleeDc: 14,
    xpReward: 16,
    goldReward: 60,
    drop: "kite_shield",
  },
  cursed_knight: {
    id: "cursed_knight",
    name: "저주받은 기사",
    description: "맹세를 어긴 대가로 갑옷 안에 갇힌 기사. 검술만은 살아 있을 때 그대로다.",
    hp: 34,
    attack: 8,
    defense: 18,
    fleeDc: 15,
    xpReward: 18,
    goldReward: 40,
    drop: "chain_shirt",
  },
  swamp_hag: {
    id: "swamp_hag",
    name: "늪지 마녀",
    description:
      "늪 한가운데 오두막에 사는 노파. 친절하게 차를 권하지만, 차에 무엇이 들었는지는 그녀만 안다.",
    hp: 36,
    attack: 8,
    defense: 17,
    fleeDc: 16,
    xpReward: 20,
    goldReward: 45,
    drop: "dream_powder",
  },
  stone_gargoyle: {
    id: "stone_gargoyle",
    name: "석상 가고일",
    description: "성당 지붕에서 내려온 돌 괴물. 칼날은 튕겨 나오고, 이쪽 뼈는 튕겨 나오지 않는다.",
    hp: 40,
    attack: 9,
    defense: 20,
    fleeDc: 17,
    xpReward: 22,
    goldReward: 0,
  },
  young_wyvern: {
    id: "young_wyvern",
    name: "어린 와이번",
    description: "아직 다 자라지 않은 와이번. 어리다는 말에 안심하기에는 이빨이 너무 크다.",
    hp: 44,
    attack: 10,
    defense: 19,
    fleeDc: 18,
    xpReward: 24,
    goldReward: 70,
  },
  mine_horror: {
    id: "mine_horror",
    name: "광산의 공포",
    description:
      "버려진 광산 깊은 곳에 사는 무언가. 광부들은 그것에 이름을 붙이지 않았다. 부르면 온다고 믿었기 때문이다.",
    hp: 48,
    attack: 10,
    defense: 20,
    fleeDc: 18,
    xpReward: 26,
    goldReward: 80,
    drop: "iron_ring",
  },
  frost_giant: {
    id: "frost_giant",
    name: "서리 거인",
    description: "북쪽 산에서 내려온 거인. 입김만으로 물이 얼고, 발걸음만으로 땅이 울린다.",
    hp: 54,
    attack: 11,
    defense: 21,
    fleeDc: 19,
    xpReward: 28,
    goldReward: 100,
    drop: "giant_cleaver",
  },
  dragon_of_ash: {
    id: "dragon_of_ash",
    name: "잿빛 용",
    description:
      "마을 하나를 재로 만든 늙은 용. 보물 위에서 잠들어 있으며, 깨우는 것은 당신의 선택이다.",
    hp: 60,
    attack: 12,
    defense: 22,
    fleeDc: 20,
    xpReward: 30,
    goldReward: 120,
    drop: "moonsteel_blade",
  },
};
