// Weapons: 6 one-hand physical, 3 two-hand physical, 2 magic, 3 ranged.
// Attack ranges: one-hand 2..7, two-hand 5..9, magic 3..6, ranged 3..6. Price 15..400.

import type { Item } from "../../engine/types";
import type { ItemId } from "../ids";

export const WEAPONS = {
  rusty_sword: {
    id: "rusty_sword",
    kind: "weapon",
    weaponKind: "physical",
    twoHanded: false,
    attack: 2,
    price: 15,
    name: "녹슨 검",
    description: "누군가 헛간 벽에 걸어두고 잊은 검. 녹이 슬었지만 찌르면 아프긴 하다.",
  },
  hunter_knife: {
    id: "hunter_knife",
    kind: "weapon",
    weaponKind: "physical",
    twoHanded: false,
    attack: 3,
    price: 40,
    name: "사냥꾼의 단검",
    description: "짐승 가죽을 벗기던 칼. 사람에게도 잘 든다는 게 문제라면 문제다.",
  },
  iron_mace: {
    id: "iron_mace",
    kind: "weapon",
    weaponKind: "physical",
    twoHanded: false,
    attack: 4,
    price: 70,
    name: "무쇠 철퇴",
    description: "머리가 무거운 무쇠 몽둥이. 기술보다는 성의로 휘두르는 물건이다.",
  },
  guard_saber: {
    id: "guard_saber",
    kind: "weapon",
    weaponKind: "physical",
    twoHanded: false,
    attack: 5,
    price: 110,
    name: "경비대 사브르",
    description:
      "도시 경비대에 지급되던 곡도. 전직 경비병이 어쩌다 이걸 팔게 됐는지는 묻지 않는 편이 좋다.",
  },
  silver_rapier: {
    id: "silver_rapier",
    kind: "weapon",
    weaponKind: "physical",
    twoHanded: false,
    attack: 6,
    price: 200,
    name: "은빛 레이피어",
    description:
      "가늘고 빠른 찌르기용 검. 귀족들의 결투장에서 흘러나왔다는데, 핏자국은 지워져 있다.",
  },
  moonsteel_blade: {
    id: "moonsteel_blade",
    kind: "weapon",
    weaponKind: "physical",
    twoHanded: false,
    attack: 7,
    price: 400,
    name: "달강철 검",
    description:
      "달빛 아래서만 벼렸다는 강철 검. 대장장이의 허풍인지 진실인지, 베어 보면 알게 된다.",
  },
  woodcutter_axe: {
    id: "woodcutter_axe",
    kind: "weapon",
    weaponKind: "physical",
    twoHanded: true,
    attack: 5,
    price: 60,
    name: "나무꾼의 도끼",
    description: "나무를 베던 양손 도끼. 나무보다 부드러운 것은 더 잘 벤다.",
  },
  pike_of_the_watch: {
    id: "pike_of_the_watch",
    kind: "weapon",
    weaponKind: "physical",
    twoHanded: true,
    attack: 7,
    price: 160,
    name: "파수대의 장창",
    description:
      "성벽 위 파수병들이 쓰던 긴 창. 상대가 닿기 전에 먼저 닿는다는 것이 최대의 미덕이다.",
  },
  giant_cleaver: {
    id: "giant_cleaver",
    kind: "weapon",
    weaponKind: "physical",
    twoHanded: true,
    attack: 9,
    price: 380,
    name: "거인의 대검",
    description:
      "사람 키만 한 쇠붙이. 거인이 썼다는 말은 거짓말이겠지만, 들어 올리면 그렇게 믿고 싶어진다.",
  },
  apprentice_wand: {
    id: "apprentice_wand",
    kind: "weapon",
    weaponKind: "magic",
    twoHanded: false,
    attack: 3,
    price: 50,
    name: "견습생의 지팡이",
    description:
      "마법 학교 견습생이 첫 학기에 받는 지팡이. 불꽃은 나오는데 방향은 약간 운에 맡긴다.",
  },
  ashwood_staff: {
    id: "ashwood_staff",
    kind: "weapon",
    weaponKind: "magic",
    twoHanded: false,
    attack: 6,
    price: 260,
    name: "물푸레나무 지팡이",
    description:
      "오래된 물푸레나무를 깎은 장식 없는 지팡이. 진짜 마법사에게 장식은 필요 없다고 전 주인이 적어 두었다.",
  },
  short_bow: {
    id: "short_bow",
    kind: "weapon",
    weaponKind: "ranged",
    twoHanded: false,
    attack: 3,
    price: 35,
    name: "단궁",
    description: "가볍고 짧은 활. 멀리는 못 가지만 가까운 것은 충분히 맞힌다.",
  },
  hunting_crossbow: {
    id: "hunting_crossbow",
    kind: "weapon",
    weaponKind: "ranged",
    twoHanded: false,
    attack: 5,
    price: 130,
    name: "사냥용 석궁",
    description: "당기는 데는 힘이 들지만 겨누는 데는 재주가 필요 없다. 그래서 인기가 많다.",
  },
  elm_longbow: {
    id: "elm_longbow",
    kind: "weapon",
    weaponKind: "ranged",
    twoHanded: false,
    attack: 6,
    price: 240,
    name: "느릅나무 장궁",
    description: "사람 키를 넘는 느릅나무 활. 제대로 당기려면 어깨가 먼저 항의한다.",
  },
} satisfies Partial<Readonly<Record<ItemId, Item>>>;
